### ISSUE TITLE
Operation not supported or available

### ISSUE THREAD

**Issue by norey** [rob-blackbourn/jetblack-negotiate-stream#2]
Testing with the following:

```py
data = bytes.fromhex(stream)

def main():
    # hostname = socket.gethostname()
    hostname = '192.168.100.50'
    port = 8989

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.connect((hostname, port))

        stream = NegotiateStream(socket.gethostname(), sock)

        # Do the client side negotiate handshake.
        stream.authenticate_as_client()

        # for data in (b'first line', b'second line', b'third line'):
            # All reads and writes are encrypted.
        stream.write(data)
        response = stream.read()
        print("Received: ", response)

if __name__ == '__main__':
    main()
```

On MacOS, fails on the `stream.authenticate_as_client()` call.

```sh
❯ python -V
Python 3.10.15

❯ python send.py
Traceback (most recent call last):
  File "/Users/user/code/send.py", line 30, in <module>
    main()
  File "/Users/user/code/send.py", line 21, in main
    stream.authenticate_as_client()
  File "/Users/user/.venv-dev/lib/python3.10/site-packages/jetblack_negotiate_stream/negotiate_stream.py", line 62, in authenticate_as_client
    out_token = self._client.step(in_token)
  File "/Users/user/.venv-dev/lib/python3.10/site-packages/spnego/_negotiate.py", line 136, in step
    mech_token_in, mech_list_mic, is_spnego = self._step_spnego_input(in_token=in_token)
  File "/Users/user/.venv-dev/lib/python3.10/site-packages/spnego/_negotiate.py", line 237, in _step_spnego_input
    self._mech_list = self._rebuild_context_list()
  File "/Users/user/.venv-dev/lib/python3.10/site-packages/spnego/_negotiate.py", line 439, in _rebuild_context_list
    raise BadMechanismError(context_msg="Unable to negotiate common mechanism", base_error=last_err)
spnego.exceptions.BadMechanismError: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism
```

**Comment by rob-blackbourn** [comment]
Hi @norey,

This is currently a Windows only package.

When a Windows client connects to a Windows server, the client exchanges it's login credentials with the server. This won't happen when connecting from a Mac.

There are a number of ways negotiate-stream can authenticate, the primary one being NTLM. For this I think the both client and server need to be on Windows.

It looks like there is some support for Kerberos in the underlying [spnego](https://github.com/jborean93/pyspnego/tree/main) package, although this is not currently supported here.

Looking at some [recent .Net issues](https://github.com/dotnet/runtime/issues/100231) it seems that it should be possible to authenticate given a username, password and domain. Again this is not currently supported here.

I don't the time to do such a deep dive right now, but I'm happy to take contributions if anyone has a solution for this.

Sorry I can't be more helpful.

Rob
